#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Atsuki Kasai
import sys  

def tomum(s)
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rtrip()

print(ans)
