#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Atsuki Kasai
# SPDX-License-Identifier: BSD-3-Clause
import sys  


def tonus(s):
    try:
        return int (s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rtrip()
    ans += tonum(line)


print(ans)
