name: Kadaitest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリのチェックアウト
      uses: actions/checkout@v3

    - name: Pythonのセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: 実行権限の付与
      run: |
        chmod +x kadai/lucky
        chmod +x kadaitest.bash

    - name: テストの実行
      run: ./kadaitest.bash

